version: "3.8"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  bitcoind:
    image: ghcr.io/sethforprivacy/bitcoind:latest
    restart: unless-stopped
    container_name: bitcoind
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - 8333:8333

  public-pool:
    container_name: public-pool
    image: ghcr.io/sethforprivacy/public-pool:latest
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "0.0.0.0:3333:3333/tcp"
    volumes:
      - "public-pool-db:/public-pool/DB"
      - "./pool.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-pool-api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.public-pool-api.loadbalancer.server.port=3334"

  public-pool-ui:
    container_name: public-pool-ui
    image: ghcr.io/sethforprivacy/public-pool-ui:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-pool-ui.rule=PathPrefix(`/`)"
      - "traefik.http.services.public-pool-ui.loadbalancer.server.port=80"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  lets-encrypt-data:
  bitcoind-data:
  public-pool-db:
